name: "Assignment 4 Part 1 Workflow"
on: [push, pull_request]
jobs:
  unit-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
      - name: Run Unit Tests
        run: |
          cd $GITHUB_WORKSPACE
          chmod +x ./unit-test.sh
          ./unit-test.sh