name: "Assignment 4 Part 1 Workflow"
on: [push, pull_request]
jobs:
  unit-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run Unit Tests
        run: |
          ./unit-test.sh
      - name: Run Full Tests
        run: |
          ./full-test.sh